name: ESP-IDF CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: esp-idf-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: esp-idf-${{ runner.os }}-

      - name: Install ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          ./install.sh
          echo "source ~/esp-idf/export.sh" >> $GITHUB_ENV

      - name: Build the Project
        run: |
          source ~/esp-idf/export.sh
          idf.py build
